#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
"""Generates Starcraft LLM instruction files from starflow source documents."""

import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

INSTRUCTIONS_DIR = Path(__file__).parent.parent

# Prefixed to each instruction file
FRONTMATTER = """\
---
applyTo: '**/*craft*/**/docs/**/*.rst, **/*craft*/**/docs/**/*.md'
---

<!-- Auto-generated by groups/starcraft/instructions/documentation/scripts/compile-llm-instructions.py. -->

"""

STARFLOW_RAW = "https://raw.githubusercontent.com/canonical/starflow/main"

EXTERNAL_SOURCES = [
    (
        f"{STARFLOW_RAW}/docs/how-to/starcraft-style-guide.rst",
        INSTRUCTIONS_DIR / "starcraft-docs-style.instructions.md",
    ),
    (
        f"{STARFLOW_RAW}/docs/how-to/add-a-page-meta-description.rst",
        INSTRUCTIONS_DIR / "starcraft-docs-meta.instructions.md",
    ),
]


def check_pandoc() -> None:
    if shutil.which("pandoc") is None:
        sys.exit("Error: cannot find pandoc. Install it with:\napt install pandoc\n")


def strip_html_blocks(text: str) -> str:
    """Remove <div> blocks pandoc emits for unrecognised RST directives like ``.. meta::``."""
    return re.sub(r"<div[^>]*>.*?</div>\n*", "", text, flags=re.DOTALL).lstrip()


def fetch_url(url: str) -> str:
    try:
        with urllib.request.urlopen(url, timeout=15) as response:
            return response.read().decode()
    except urllib.error.HTTPError as e:
        sys.exit(f"Error fetching {url}: HTTP {e.code} {e.reason}")
    except urllib.error.URLError as e:
        sys.exit(f"Error fetching {url}: {e.reason}")


def rst_to_markdown(rst_content: str) -> str:
    """Convert RST content to Markdown with pandoc via stdin."""
    try:
        result = subprocess.run(
            ["pandoc", "--from", "rst", "--to", "gfm", "--wrap=none"],
            input=rst_content,
            capture_output=True,
            text=True,
            check=True,
            timeout=15,
        )
    except subprocess.CalledProcessError as e:
        sys.exit(f"Error: pandoc exited with code {e.returncode}\n{e.stderr}")
    return strip_html_blocks(result.stdout)


def write_instruction_file(dst: Path, content: str) -> None:
    dst.write_text(FRONTMATTER + content)
    print(f"  Wrote {dst.name}")


def main() -> None:
    check_pandoc()

    print("Fetching and converting sources from canonical/starflow.")
    for url, dst in EXTERNAL_SOURCES:
        print(f"  Fetching {url}")
        write_instruction_file(dst, rst_to_markdown(fetch_url(url)))

    print("Done.")


if __name__ == "__main__":
    main()
